import os
from datetime import datetime
from typing import Optional
from pathlib import Path

import structlog

logger = structlog.get_logger()

CHANGE_ORDER_HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: 'Georgia', serif; margin: 0; padding: 40px; color: #1a1a1a; }}
  .header {{ border-bottom: 3px solid #2563eb; padding-bottom: 20px; margin-bottom: 30px; }}
  .company-name {{ font-size: 24px; font-weight: bold; color: #2563eb; }}
  .doc-title {{ font-size: 20px; margin: 10px 0; }}
  .meta-table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
  .meta-table td {{ padding: 8px 12px; border: 1px solid #e5e7eb; }}
  .meta-table td:first-child {{ font-weight: bold; background: #f9fafb; width: 35%; }}
  .section {{ margin: 25px 0; }}
  .section h3 {{ color: #2563eb; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; }}
  .scope-box {{ background: #fef3c7; border-left: 4px solid #f59e0b; padding: 15px; margin: 15px 0; }}
  .cost-table {{ width: 100%; border-collapse: collapse; }}
  .cost-table th {{ background: #2563eb; color: white; padding: 10px 15px; text-align: left; }}
  .cost-table td {{ padding: 10px 15px; border-bottom: 1px solid #e5e7eb; }}
  .total-row td {{ font-weight: bold; background: #f9fafb; font-size: 16px; }}
  .signature-block {{ margin-top: 60px; display: flex; gap: 60px; }}
  .sig-line {{ border-top: 1px solid #1a1a1a; width: 250px; padding-top: 8px; font-size: 12px; color: #6b7280; }}
  .footer {{ margin-top: 40px; font-size: 11px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 15px; }}
  .badge {{ display: inline-block; background: #fee2e2; color: #dc2626; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: bold; }}
</style>
</head>
<body>

<div class="header">
  <div class="company-name">{freelancer_name}</div>
  <div class="doc-title">Change Order Request</div>
  <div>CO-{co_number} &nbsp;|&nbsp; <span class="badge">PENDING APPROVAL</span></div>
</div>

<table class="meta-table">
  <tr><td>Change Order #</td><td>CO-{co_number}</td></tr>
  <tr><td>Date Issued</td><td>{date_issued}</td></tr>
  <tr><td>Project</td><td>{project_title}</td></tr>
  <tr><td>Client</td><td>{client_name}</td></tr>
</table>

<div class="section">
  <h3>Description</h3>
  <p>{description}</p>
</div>

<div class="section">
  <h3>Additional Scope of Work</h3>
  <div class="scope-box">
    <strong>New Work Being Added:</strong>
    <p>{scope_addition}</p>
  </div>
</div>

<div class="section">
  <h3>Cost Summary</h3>
  <table class="cost-table">
    <thead>
      <tr><th>Item</th><th>Hours</th><th>Rate</th><th>Amount</th></tr>
    </thead>
    <tbody>
      <tr>
        <td>{scope_addition_short}</td>
        <td>{estimated_hours}</td>
        <td>${hourly_rate}/hr</td>
        <td>${subtotal:,.2f}</td>
      </tr>
      <tr class="total-row">
        <td colspan="3"><strong>Total Additional Cost</strong></td>
        <td><strong>${total_cost:,.2f}</strong></td>
      </tr>
    </tbody>
  </table>
</div>

<div class="section">
  <h3>Terms</h3>
  <p>{terms}</p>
</div>

{professional_note_section}

<div class="signature-block">
  <div>
    <div class="sig-line">Freelancer / Agency Signature &amp; Date</div>
    <div style="margin-top:8px; font-size:13px;">{freelancer_name}</div>
  </div>
  <div>
    <div class="sig-line">Client Signature &amp; Date</div>
    <div style="margin-top:8px; font-size:13px;">{client_name}</div>
  </div>
</div>

<div class="footer">
  This change order was automatically generated by ScopeGuard AI. 
  Once signed by both parties, this document amends the original contract and authorizes the additional work and billing described herein.
  Generated on {date_issued}.
</div>

</body>
</html>
"""


def generate_change_order_pdf(
    co_data: dict,
    output_path: str,
) -> bool:
    """Generate a PDF change order using WeasyPrint."""
    try:
        from weasyprint import HTML
        
        professional_note = co_data.get("professional_note", "")
        note_section = ""
        if professional_note:
            note_section = f"""
            <div class="section">
              <h3>Note</h3>
              <p>{professional_note}</p>
            </div>"""
        
        scope_short = co_data["scope_addition"][:80] + "..." if len(co_data["scope_addition"]) > 80 else co_data["scope_addition"]
        
        html_content = CHANGE_ORDER_HTML_TEMPLATE.format(
            freelancer_name=co_data["freelancer_name"],
            co_number=co_data["co_number"],
            date_issued=co_data["date_issued"],
            project_title=co_data["project_title"],
            client_name=co_data["client_name"],
            description=co_data["description"],
            scope_addition=co_data["scope_addition"],
            scope_addition_short=scope_short,
            estimated_hours=co_data["estimated_hours"],
            hourly_rate=co_data["hourly_rate"],
            subtotal=co_data["estimated_hours"] * co_data["hourly_rate"],
            total_cost=co_data["total_cost"],
            terms=co_data.get("terms", "Payment due within 15 days of approval."),
            professional_note_section=note_section,
        )
        
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        HTML(string=html_content).write_pdf(output_path)
        logger.info("pdf_generated", path=output_path)
        return True
        
    except ImportError:
        logger.warning("weasyprint_not_available_generating_html", path=output_path)
        # Fall back to saving HTML
        html_path = output_path.replace(".pdf", ".html")
        Path(html_path).parent.mkdir(parents=True, exist_ok=True)
        with open(html_path, "w") as f:
            f.write(CHANGE_ORDER_HTML_TEMPLATE.format(
                freelancer_name=co_data["freelancer_name"],
                co_number=co_data["co_number"],
                date_issued=co_data["date_issued"],
                project_title=co_data["project_title"],
                client_name=co_data["client_name"],
                description=co_data["description"],
                scope_addition=co_data["scope_addition"],
                scope_addition_short=co_data["scope_addition"][:80],
                estimated_hours=co_data["estimated_hours"],
                hourly_rate=co_data["hourly_rate"],
                subtotal=co_data["estimated_hours"] * co_data["hourly_rate"],
                total_cost=co_data["total_cost"],
                terms=co_data.get("terms", "Payment due within 15 days of approval."),
                professional_note_section="",
            ))
        return True
    except Exception as e:
        logger.error("pdf_generation_error", error=str(e))
        return False