"""
PR Bot — opens GitHub or GitLab pull requests with fix proposals.
Falls back to mock mode for development.
"""
import json
from typing import Optional, Dict, Any
import structlog

from app.config import settings

logger = structlog.get_logger()


async def create_github_pr(
    repo: str,
    fix_proposal_id: int,
    test_name: str,
    root_cause: str,
    patch_diff: str,
    explanation: str,
    confidence: float,
    base_branch: str = "main",
) -> Dict[str, Any]:
    """Create a GitHub pull request with the fix proposal."""
    if settings.mock_github or not settings.github_token:
        return _mock_pr_response(repo, fix_proposal_id, test_name, root_cause)
    
    import httpx
    
    headers = {
        "Authorization": f"Bearer {settings.github_token}",
        "Accept": "application/vnd.github.v3+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    
    # 1. Create a new branch
    branch_name = f"flaky-fix/{fix_proposal_id}/{test_name.replace('/', '_')[:40]}"
    
    async with httpx.AsyncClient() as client:
        # Get default branch SHA
        ref_resp = await client.get(
            f"https://api.github.com/repos/{repo}/git/ref/heads/{base_branch}",
            headers=headers,
        )
        if ref_resp.status_code != 200:
            raise Exception(f"Failed to get branch ref: {ref_resp.text}")
        
        sha = ref_resp.json()["object"]["sha"]
        
        # Create branch
        await client.post(
            f"https://api.github.com/repos/{repo}/git/refs",
            headers=headers,
            json={"ref": f"refs/heads/{branch_name}", "sha": sha},
        )
        
        # Create PR
        pr_body = _build_pr_body(
            test_name=test_name,
            root_cause=root_cause,
            patch_diff=patch_diff,
            explanation=explanation,
            confidence=confidence,
        )
        
        pr_resp = await client.post(
            f"https://api.github.com/repos/{repo}/pulls",
            headers=headers,
            json={
                "title": f"🧪 Fix flaky test: {test_name.split('::')[-1]} ({root_cause})",
                "body": pr_body,
                "head": branch_name,
                "base": base_branch,
            },
        )
        
        if pr_resp.status_code not in (200, 201):
            raise Exception(f"Failed to create PR: {pr_resp.text}")
        
        pr_data = pr_resp.json()
        return {
            "pr_url": pr_data["html_url"],
            "pr_number": pr_data["number"],
        }


def _build_pr_body(
    test_name: str,
    root_cause: str,
    patch_diff: str,
    explanation: str,
    confidence: float,
) -> str:
    """Build a rich PR description with fix context."""
    confidence_emoji = "🟢" if confidence > 0.8 else "🟡" if confidence > 0.6 else "🔴"
    
    return f"""## 🔬 Flaky Test Fix Proposal

**Generated by:** Flaky Test Root-Cause Attribution System  
**Test:** `{test_name}`  
**Root Cause:** `{root_cause}`  
**Confidence:** {confidence_emoji} {confidence:.0%}

---

## Analysis

{explanation}

---

## Proposed Fix

```diff
{patch_diff}
```

---

## How to Review

1. ✅ If this fix looks correct, approve and merge
2. 🔄 Run the CI pipeline to verify the fix eliminates flakiness
3. ❌ If incorrect, close this PR with a comment explaining why

---

*This PR was automatically generated by the Flaky Test Detector. 
Please provide feedback to improve future fix proposals.*

<!-- flaky-fix-proposal-id: auto -->
"""


def _mock_pr_response(
    repo: str,
    fix_proposal_id: int,
    test_name: str,
    root_cause: str,
) -> Dict[str, Any]:
    """Mock PR response for development mode."""
    pr_number = 1000 + fix_proposal_id
    return {
        "pr_url": f"https://github.com/{repo}/pull/{pr_number}",
        "pr_number": pr_number,
        "mock": True,
    }


async def post_fix_proposal(
    repo: str,
    fix_proposal_id: int,
    test_name: str,
    root_cause: str,
    patch_diff: str,
    explanation: str,
    confidence: float,
    base_branch: str = "main",
) -> Dict[str, Any]:
    """Main entry point for PR creation."""
    try:
        result = await create_github_pr(
            repo=repo,
            fix_proposal_id=fix_proposal_id,
            test_name=test_name,
            root_cause=root_cause,
            patch_diff=patch_diff,
            explanation=explanation,
            confidence=confidence,
            base_branch=base_branch,
        )
        logger.info(
            "pr_created",
            repo=repo,
            pr_url=result.get("pr_url"),
            mock=result.get("mock", False),
        )
        return result
    except Exception as e:
        logger.error("pr_creation_failed", error=str(e), repo=repo)
        # Return mock on failure
        return _mock_pr_response(repo, fix_proposal_id, test_name, root_cause)